### ISSUE TITLE
Desired target point in run_cbf_clf_simulation_dubins_car.m

### ISSUE THREAD

**Issue by Ramune6110** [HybridRobotics/CBF-CLF-Helper#4]
Regarding run_cbf_clf_simulation_dubins_car.m, there is no change even if I change the Desired target point params.xd and params.yd. Is there a bug in the program that does not take the Desired target point into account?

**Comment by Ramune6110** [comment]
I misunderstood, you are applying a function that takes the target value and deviation on the CLF side, and you are considering the constraints you want to protect on the CBF side.

**Comment by ChoiJangho** [comment]
<img width="1111" alt="Screen Shot 2021-08-03 at 1 32 31 AM" src="https://user-images.githubusercontent.com/13898637/127984371-bbe2ee5a-72ea-4c2e-9c83-106f6074b5b0.png">
Correct, so the left plot is with params.xd = 12, params.yd = 0, and the right plot is with params.xd=14, params.yd = 6, and they are giving different results. Note that for the Dubins car system, because of its nonholonomic dynamics, it does not always converge to the exact target point. You can also play around with different clf and cbf rates.

**Comment by Ramune6110** [comment]
Thanks for the thoughtful response!
